# Generated by Django 5.1 on 2024-08-22 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_creator', '0002_rename_cotribution_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='story_creator.story'),
        ),
    ]
