# Generated by Django 5.1 on 2024-08-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_creator', '0006_story_first_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
