# Generated by Django 5.1 on 2024-08-27 06:37

import story_creator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_creator', '0007_alter_story_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='content',
            field=models.CharField(max_length=200, validators=[story_creator.models.validate_max_words]),
        ),
    ]
